#!/usr/bin/env python3
"""What is running across the portfolio, and a page a human can read.

Two artifacts, and the split is deliberate:

  ~/.claude/harbourmaster/          live state — berth locks, event journal
  ~/Dev/FLEET.md                    a rendered snapshot beside ARMADA.md

ARMADA.md is curated and skim-read; this is written many times a minute by many
sessions at once. mac-doctor keeps a JSONL ledger the same way and has a
`.corrupt-backup` file on disk from concurrent writes, which is the evidence for
keeping the hot path off any file a human also edits.

The occupancy half of this is not stored at all — it is read from the berth
locks, so it cannot drift from reality or survive the process that made it.
"""
from __future__ import annotations

import fcntl
import json
import os
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import berths  # noqa: E402

HOME = berths.HOME
JOURNAL = HOME / "events.jsonl"
FLEET_MD = Path(os.environ.get("HARBOURMASTER_FLEET_MD",
                               Path.home() / "Dev/FLEET.md"))


def record(event: dict) -> None:
    """Append one event under an exclusive lock.

    O_APPEND alone is atomic only up to PIPE_BUF and only for a single write;
    the lock is what makes a line from one session never land inside a line
    from another.
    """
    HOME.mkdir(parents=True, exist_ok=True)
    event = {"at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
             "pid": os.getpid(), **event}
    fd = os.open(JOURNAL, os.O_WRONLY | os.O_CREAT | os.O_APPEND)
    try:
        fcntl.flock(fd, fcntl.LOCK_EX)
        os.write(fd, (json.dumps(event) + "\n").encode())
    finally:
        fcntl.flock(fd, fcntl.LOCK_UN)
        os.close(fd)


def recent(limit: int = 40) -> list[dict]:
    try:
        lines = JOURNAL.read_text().splitlines()[-limit:]
    except OSError:
        return []
    out = []
    for line in lines:
        try:
            out.append(json.loads(line))
        except ValueError:
            continue  # a torn line is skipped, never guessed at
    return out


def render(report: dict, thermal: dict | None = None) -> str:
    pressure = report["pressure"]
    bar = {"healthy": "●○○○", "busy": "●●○○", "tight": "●●●○",
           "critical": "●●●●", "unknown": "????"}

    by_project: dict[str, list[dict]] = {}
    for occupant in report["occupants"]:
        by_project.setdefault(occupant.get("project", "unknown"), []).append(occupant)

    lines = [
        "# FLEET — what this Mac is carrying",
        "",
        "Generated by the `harbourmaster` skill. Live state lives in "
        "`~/.claude/harbourmaster/`; this file is a rendered snapshot and is "
        "safe to delete. The manifest of record for projects is `ARMADA.md`.",
        "",
        f"**Sampled** {report['sampled_at']} · "
        f"**berths** {report['in_use']}/{report['ceiling']} in use "
        f"(capacity {report['capacity']}) · "
        f"**load/core** {report['load_per_core']}",
        "",
        "## Pressure",
        "",
        "| Axis | State | |",
        "|---|---|---|",
    ]
    for axis in ("cpu", "memory", "disk"):
        state = pressure[axis]
        lines.append(f"| {axis} | {state} | {bar.get(state, '')} |")
    lines.append(f"| **overall** | **{pressure['overall']}** | "
                 f"{bar.get(pressure['overall'], '')} |")

    if report.get("hard_gate"):
        gate = report["hard_gate"]
        lines += ["", f"> **Admission closed on {gate['axis']}** — {gate['reason']}"]

    lines += ["", "## Projects holding berths", ""]
    if by_project:
        lines += ["| Project | Berths | Work |", "|---|---|---|"]
        for project, entries in sorted(by_project.items()):
            labels = sorted({e.get("label") or e.get("command", "")[:40]
                             for e in entries})
            lines.append(f"| {project} | {len(entries)} | {'; '.join(labels)} |")
    else:
        lines.append("*No governed work running.* Note this counts only work "
                     "started through `governor-run` — anything launched around "
                     "the wrapper is invisible here and ungoverned.")

    if thermal:
        lines += ["", "## Thermal", "",
                  f"**{thermal.get('verdict', 'unknown')}** — "
                  f"{thermal.get('reason', '')}"]
        if thermal.get("action") not in (None, "none", ""):
            lines.append(f"Action taken: `{thermal['action']}` "
                         f"{thermal.get('detail', '')}")

    events = recent(12)
    if events:
        lines += ["", "## Recent events", "", "| When | Event | Detail |",
                  "|---|---|---|"]
        for event in reversed(events):
            detail = event.get("detail") or event.get("project") or ""
            lines.append(f"| {event['at']} | {event.get('kind', '?')} | {detail} |")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = sys.argv[1:]
    if args and args[0] == "record":
        record(json.loads(args[1]) if len(args) > 1 else {"kind": "ping"})
        return 0

    report = berths.report()
    thermal = None
    if "--with-thermal" in args:
        import subprocess
        out = subprocess.run(
            [sys.executable, str(Path(__file__).with_name("thermal.py")),
             "--duration", "10"],
            capture_output=True, text=True, timeout=180)
        try:
            thermal = json.loads(out.stdout)
        except ValueError:
            thermal = None

    text = render(report, thermal)
    if "--stdout" in args:
        sys.stdout.write(text)
        return 0
    FLEET_MD.parent.mkdir(parents=True, exist_ok=True)
    tmp = FLEET_MD.with_suffix(".md.tmp")
    tmp.write_text(text)
    tmp.replace(FLEET_MD)   # atomic: a reader never sees a half-written page
    print(str(FLEET_MD))
    return 0


if __name__ == "__main__":
    sys.exit(main())
