#!/usr/bin/env python3
"""Emit the Dossier/Margin marketing chrome for a report page.

Two blocks, deliberately different in register, both carrying the same two
marks:

  colophon  a sticky masthead. Discreet: the marks, one flag, one sentence.
  closer    a full band at the foot of the page. Overt: a headline, a
            paragraph, and a facts list.

That split is not decoration. It is the shape the pages settled on after
"the dossier page still needs to discretely market margin, and have a
section at the bottom that's more overt".

The chrome is the ONE part of a report page that stays constant between
topics, so it ships as a script rather than as prose to copy. Everything
else on the page is designed from scratch per topic.

Usage:
    python3 build_chrome.py spec.json > chrome.html

spec.json keys (all optional except closer_h and closer_p):
    flag         short uppercase tag in the masthead, e.g. "Not medical advice"
    lead         one sentence beside it
    closer_h     the closing headline
    closer_p     the closing paragraph
    facts        list of [term, definition] pairs
    ground       masthead background      (default #14100E)
    paper        masthead foreground      (default #F0E6CE)
    accent       the 3px rule + flag fill (default #C43A2B)
    maxw_var     CSS var holding the page's max width (default --maxw)

The palette defaults are the Dossier/Margin house tokens. Override all
three when the page's own palette would otherwise fight the bar: the
chrome should read as a publisher's mark on the page, not as a fragment
of a different website.
"""

from __future__ import annotations

import base64
import html
import json
import pathlib
import sys

ASSETS = pathlib.Path(__file__).resolve().parent

MARKS = (
    ("dossier", "Dossier", "https://github.com/fledgeling-co/dossier-research-mcp"),
    ("margin", "Margin", "https://margin.fledgeling.app/"),
)


def data_uri(slug: str) -> str:
    """Inline the mark. These pages are single self-contained files, so a
    second request for a 3KB logo is a request that can fail on its own."""
    svg = (ASSETS / f"{slug}-mark.svg").read_bytes()
    return "data:image/svg+xml;base64," + base64.b64encode(svg).decode("ascii")


def esc(s: str) -> str:
    return html.escape(str(s), quote=True)


def build(spec: dict) -> str:
    ground = spec.get("ground", "#14100E")
    paper = spec.get("paper", "#F0E6CE")
    accent = spec.get("accent", "#C43A2B")
    maxw = spec.get("maxw_var", "--maxw")
    flag = spec.get("flag", "")
    lead = spec.get("lead", "Compiled with Dossier and Margin.")
    facts = spec.get("facts", [])

    for key in ("closer_h", "closer_p"):
        if not spec.get(key):
            raise SystemExit(f"build_chrome.py: {key} is required in the spec")

    uris = {slug: data_uri(slug) for slug, _, _ in MARKS}

    masthead_marks = []
    for i, (slug, label, href) in enumerate(MARKS):
        if i:
            masthead_marks.append('      <span class="mk-sep"></span>')
        masthead_marks.append(
            f'      <a class="mk" href="{href}" target="_blank" rel="noopener">\n'
            f'        <img src="{uris[slug]}" width="26" height="26" alt="" loading="lazy">\n'
            f"        <b>{esc(label)}</b>\n"
            f"      </a>"
        )

    closer_marks = "\n".join(
        f'      <a href="{href}" target="_blank" rel="noopener" aria-label="{esc(label)}">'
        f'<img src="{uris[slug]}" width="30" height="30" alt="" loading="lazy"></a>'
        for slug, label, href in MARKS
    )

    facts_html = "\n".join(
        f"      <dt>{esc(t)}</dt><dd>{esc(d)}</dd>" for t, d in facts
    )

    flag_html = f'<span class="colophon-flag">{esc(flag)}</span>\n        ' if flag else ""

    return f"""<!-- ============================================================
     MARKETING CHROME - generated by build_chrome.py, do not hand-edit.
     Publisher chrome in the Dossier / Margin house style, deliberately
     NOT the page's own design system. It reads as a masthead stamped on
     the page rather than as part of it.
     ============================================================ -->
<style>
.colophon{{
  position:sticky; top:0; z-index:150;
  background:{ground}; color:{paper};
  font-family:'Bricolage Grotesque','Albert Sans',system-ui,sans-serif;
  border-bottom:3px solid {accent};
  transition:transform 260ms cubic-bezier(.2,.7,.3,1);
}}
.colophon.tucked{{transform:translateY(-100%)}}
.colophon-in{{max-width:var({maxw},1120px);margin:0 auto;padding:10px 24px;
  display:flex;align-items:center;gap:24px}}
.colophon-marks{{display:flex;align-items:center;gap:16px}}
.mk{{display:flex;align-items:center;gap:8px;white-space:nowrap;text-decoration:none;
  transition:opacity .18s ease,transform .12s cubic-bezier(.2,.7,.3,1)}}
.mk:hover{{opacity:.72}}
.mk:active{{transform:scale(.97)}}
.mk:focus-visible{{outline:2px solid {accent};outline-offset:3px}}
.mk img,.closer-mark img{{display:block;border-radius:5px;
  box-shadow:0 0 0 1px rgba(240,230,206,.42),0 2px 8px rgba(0,0,0,.45)}}
.mk b{{font-family:'Space Mono',ui-monospace,monospace;font-size:11px;font-weight:700;
  letter-spacing:.1em;text-transform:uppercase;color:{paper}}}
.mk-sep{{width:1px;height:22px;background:rgba(240,230,206,.16)}}
.colophon-body{{min-width:0}}
.colophon-lead{{margin:0;font-size:13.5px;line-height:1.35;color:{paper}}}
.colophon-flag{{display:inline-block;font-family:'Space Mono',ui-monospace,monospace;
  font-size:9.5px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;
  background:{accent};color:#FFF3F1;padding:3px 7px;margin-right:9px;
  vertical-align:1px;white-space:nowrap}}
.closer{{background:{ground};color:{paper};border-top:3px solid {accent}}}
.closer-in{{max-width:var({maxw},1120px);margin:0 auto;padding:64px 24px;
  display:grid;grid-template-columns:auto 1fr auto;gap:32px;align-items:start}}
.closer-mark{{display:flex;gap:10px;padding-top:4px}}
.closer-mark a{{transition:opacity .18s ease}}
.closer-mark a:hover{{opacity:.72}}
.closer-mark a:focus-visible{{outline:2px solid {accent};outline-offset:3px}}
.closer-h{{font-family:'Bricolage Grotesque',sans-serif;font-size:clamp(22px,2.6vw,30px);
  line-height:1.14;margin:0 0 12px;font-weight:600}}
.closer-p{{margin:0;font-size:15px;line-height:1.55;opacity:.8;max-width:52ch}}
.closer-facts{{margin:0;display:grid;grid-template-columns:auto 1fr;gap:8px 16px;
  border-left:1px solid rgba(240,230,206,.16);padding-left:32px}}
.closer-facts dt{{font-family:'Space Mono',ui-monospace,monospace;font-size:10px;
  font-weight:700;letter-spacing:.1em;text-transform:uppercase;opacity:.62;white-space:nowrap}}
.closer-facts dd{{margin:0;font-size:13.5px;line-height:1.4;color:{paper}}}
@media (max-width:820px){{
  .colophon-in{{flex-wrap:wrap;gap:12px 16px;padding:9px 24px}}
  .mk-sep{{display:none}}
  .colophon-lead{{font-size:12.5px;flex:1 1 100%}}
  .closer-in{{grid-template-columns:1fr;gap:24px}}
  .closer-facts{{border-left:0;border-top:1px solid rgba(240,230,206,.16);
    padding-left:0;padding-top:24px}}
}}
@media (prefers-reduced-motion:reduce){{
  .colophon{{transition:none}}.colophon.tucked{{transform:none}}
  .mk:active{{transform:none}}
}}
@media print{{
  .colophon{{position:static;background:#FDFDFC;color:#111110;border-bottom:2px solid #111110}}
  .colophon-lead,.mk b{{color:#111110}}
  .closer{{background:#FDFDFC;color:#111110;border-top:2px solid #111110}}
  .closer-h{{color:#111110}}.closer-p,.closer-facts dd{{color:#333331}}
}}
</style>

<header class="colophon">
  <div class="colophon-in">
    <div class="colophon-marks">
{chr(10).join(masthead_marks)}
    </div>
    <div class="colophon-body">
      <p class="colophon-lead">
        {flag_html}{esc(lead)}
      </p>
    </div>
  </div>
</header>

<!-- place immediately before </body>, after the sources list -->
<section class="closer">
  <div class="closer-in">
    <div class="closer-mark">
{closer_marks}
    </div>
    <div class="closer-main">
      <h2 class="closer-h">{esc(spec["closer_h"])}</h2>
      <p class="closer-p">{esc(spec["closer_p"])}</p>
    </div>
    <dl class="closer-facts">
{facts_html}
    </dl>
  </div>
</section>
"""


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    spec = json.loads(pathlib.Path(sys.argv[1]).read_text())
    sys.stdout.write(build(spec))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
