#!/usr/bin/env python3
"""audit_run.py — the gate that makes a review's own numbers checkable.

Two modes, both exiting non-zero when the review is about to assert something it
did not measure.

    python3 scripts/audit_run.py capability <workdir>
    python3 scripts/audit_run.py claims <workdir> --report <report.md>

**capability** answers "which of this run's zeros are real?". It reads
`probes/*.json`, splits every headline metric into measured / declared /
unmeasurable, and exits 1 while any metric the report is likely to quote is
unmeasurable and therefore unquotable as a count.

The failure it exists to catch, measured on this skill 18 Aug 2026: five
systematisation metrics read computed properties that return `""` or `0px` on
the review engine whatever the CSS says. `0 distinct radii` and `0 shadows` came
out of a page carrying two radii and a shadow, and read as a perfectly tokenised
surface. Nothing in the pipeline noticed, because a metric measuring nothing and
a surface with nothing produce the same number. Prose cannot fix that; only a
gate over the output can.

**claims** answers "is every number in the report in the manifest?". It parses
the written report for quantified assertions — "47 buttons", "12 crops",
"3 of 14 surfaces", contrast ratios — and checks each against what the run
actually recorded. A count the manifest cannot support is reported with the
manifest's own figure beside it.

The evidence for that mode is direct: W3C's ACT Rules Format defines
target-level outcomes so a claim can be traced to a target, and the research this
skill was rebuilt on recommends exactly this validator — "if an agent flags a
finding but fails to cite a nodeId that was demonstrably in the context window,
the orchestration layer dismisses the finding", and "require a `target_count`
field generated by code, never prose". A model completing the *shape* of a
review will supply a plausible number; this is what makes the number cost
something.

Neither mode judges design. They judge whether the review is entitled to its own
numbers.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Metrics a report routinely quotes as a count, and the probe field each needs.
# A metric here that comes back unmeasurable must be named in the report as
# unmeasurable rather than printed as a number.
QUOTABLE = {
    "radii": "distinct border radii",
    "shadows": "distinct shadows",
    "durations": "distinct transition durations",
    "uppercase_untracked": "untracked uppercase runs",
    "transition_all": "`transition: all` uses",
    "gap": "grid and flex gaps",
}


def load_probes(workdir: Path) -> dict[str, dict]:
    d = workdir / "probes"
    if not d.is_dir():
        sys.exit(f"No probes/ directory under {workdir}. Run run_review.py first.")
    out = {}
    for f in sorted(d.glob("*.json")):
        try:
            out[f.stem] = json.loads(f.read_text())
        except json.JSONDecodeError as e:
            print(f"! {f.name} is not valid JSON ({e}) — counted as a probe that did not run",
                  file=sys.stderr)
            out[f.stem] = {}
    if not out:
        sys.exit(f"No probe JSON under {d}. Nothing was checked — this is not a clean result.")
    return out


def cmd_capability(args) -> int:
    workdir = Path(args.workdir).resolve()
    probes = load_probes(workdir)

    print(f"Capability audit — {len(probes)} viewport(s) under {workdir}\n")
    problems: list[str] = []
    unreadable_union: set[str] = set()
    not_run: list[str] = []

    for tag, p in probes.items():
        cap = p.get("capability") or {}
        chans = cap.get("unreadable") or []
        unreadable_union.update(chans)
        if p.get("probeErrors"):
            not_run.append(f"{tag}: {'; '.join(p['probeErrors'])}")

        # Contrast is the flagship gate, so its four populations are checked by
        # name. A failure count with no denominator beside it is the shape that
        # cannot be told apart from a probe that never ran.
        c = p.get("contrast")
        if c is None:
            problems.append(f"{tag}: contrast probe did not run — its absence must be "
                            f"reported, never summarised as zero failures")
        elif isinstance(c, dict):
            ex = c.get("examined")
            if not ex:
                problems.append(f"{tag}: contrast examined 0 text nodes. A gate with an "
                                f"empty denominator did not run.")
            ct = c.get("unresolvedCount") or 0
            print(f"  {tag:>10}  contrast: {c.get('failureCount')} fail · "
                  f"{c.get('passCount')} pass · {ct} cantTell · of {ex} examined")
            if ct:
                print(f"{'':>12}  {ct} backdrop(s) unresolvable — these are neither "
                      f"passes nor failures and belong in the report as their own number")
            if c.get("gradientJudgedCount"):
                print(f"{'':>12}  {c['gradientJudgedCount']} judged against declared "
                      f"gradient stops (worst stop). Weaker than a computed opaque "
                      f"backdrop; label it.")
        else:
            problems.append(f"{tag}: contrast is a {type(c).__name__}, not the "
                            f"four-population object this build emits. Stale probes.js?")

    if unreadable_union:
        print(f"\n  {len(unreadable_union)} channel(s) this engine would not answer:")
        for c in sorted(unreadable_union):
            print(f"    - {c}")

    # The style metrics, via analyze_styles' own provenance block if it was run,
    # otherwise recomputed from the `*_src` tags dumpStyles writes.
    dark, declared = set(), set()
    for tag, p in probes.items():
        styles = p.get("styles")
        if not styles:
            not_run.append(f"{tag}: dumpStyles did not run")
            continue
        for metric, key in (("radii", "borderRadius"), ("shadows", "boxShadow"),
                            ("durations", "transitionDuration"), ("gap", "gap"),
                            ("uppercase_untracked", "textTransform"),
                            ("transition_all", "transitionProperty")):
            srcs = {n.get(key + "_src") for n in styles if isinstance(n, dict)}
            srcs.discard(None)
            if srcs and srcs <= {"unreadable"}:
                dark.add(metric)
            elif "declared" in srcs or "unreadable" in srcs:
                declared.add(metric)

    if dark:
        print(f"\n  UNMEASURABLE metrics — a count for these is not evidence:")
        for m in sorted(dark):
            print(f"    - {m} ({QUOTABLE.get(m, m)})")
            problems.append(f"{m} is unmeasurable on this engine. Report it as "
                            f"unmeasurable; do not print a count.")
    if declared - dark:
        print(f"\n  DECLARED-ONLY metrics — real counts, but of declared intent "
              f"rather than the resolved cascade:")
        for m in sorted(declared - dark):
            print(f"    - {m} ({QUOTABLE.get(m, m)})")

    if not_run:
        print(f"\n  {len(not_run)} probe(s) did not run:")
        for n in not_run:
            print(f"    - {n}")
        problems.extend(not_run)

    print()
    if problems:
        print(f"FAIL — {len(problems)} item(s) the report must declare rather than "
              f"quote as a measurement:", file=sys.stderr)
        for p in problems:
            print(f"  · {p}", file=sys.stderr)
        print("\nEvery one is a check whose clean output is indistinguishable from a "
              "real one.\nName them in 'Not checked' and the Coverage block, then "
              "re-run this.", file=sys.stderr)
        return 1
    print("PASS — every headline metric was either measured or is declared as not measured.")
    return 0


# A quantified assertion in prose, and the manifest field that can support it.
CLAIM_PATTERNS = [
    # Both orders, because a Coverage block writes "Component types: 31 of 83"
    # while prose writes "31 of 83 component types".
    ("component_types", re.compile(r"(\d+)\s+of\s+(\d+)\s+component\s+types?", re.I)),
    ("component_types", re.compile(r"component\s+types?\s*:?\s*(\d+)\s+of\s+(\d+)", re.I)),
    ("contrast_ratio", re.compile(r"(\d+(?:\.\d+)?)\s*:\s*1\b")),
    ("surfaces", re.compile(r"(\d+)\s+of\s+(\d+)\s+surfaces?", re.I)),
    ("contrast_failures", re.compile(r"(\d+)\s+contrast\s+failur", re.I)),
    ("examined", re.compile(r"of\s+(\d+)\s+examined", re.I)),
]

# The canonical fabrication: a confident population count over an element type
# nobody counted. Named because it is the shape a model reaches for when it knows
# the form of a review and has not run the procedure — "47 buttons ... audited",
# where nothing in the run produced the number 47.
ELEMENT_NOUNS = (r"buttons?|links?|inputs?|fields?|icons?|cards?|headings?|images?|"
                 r"form\s+controls?|interactive\s+elements?|components?|elements?")
ELEMENT_CLAIM = re.compile(rf"\b(\d+)\s+({ELEMENT_NOUNS})\b", re.I)

# WCAG 2.x contrast floors. A report writing "needs 4.5:1" or "the AA floor for
# large text is 3:1" is citing a requirement, and a gate that reads those as
# claims fires on every correctly-cited threshold in the document. No real
# measurement lands exactly on a floor, and one that did would be a pass at the
# boundary — uninteresting either way.
WCAG_THRESHOLDS = {3.0, 4.5, 7.0}

# A ratio can appear in a report for three reasons, and only one of them is a
# claim about the page as it stands.
#
# 1. A measurement of the current surface — checkable, and what this gate is for.
# 2. A THRESHOLD being cited ("needs 4.5:1"). Handled by WCAG_THRESHOLDS above.
# 3. A ratio attached to a PROPOSED replacement colour — "→ Should be: #4338CA on
#    white, 8.3:1". That is not on the page yet, so no probe can have recorded it.
#
# Reason 3 matters more than it looks, because `severity-and-report.md` *requires*
# it: "PrimaryButton: `#6B7280` → `var(--color-brand-primary)` (`#2563EB`);
# contrast against white text 3.8:1 → 8.6:1". Measured 18 Aug 2026, this gate
# flagged eight such figures as fabrications on a report that had done exactly
# what the skill asked, and had said so in its own text. A gate that punishes the
# mandated finding format is one nobody will keep running.
FIX_CONTEXT = re.compile(
    r"(→|->|should be|would be|change to|changing to|replace|swap|proposed|"
    r"instead of|raises? (?:it )?to|takes? (?:it )?to|gives?|lift(?:s|ing)? (?:it )?to|"
    r"not yet on the page|as a shape)", re.I)

# Non-text contrast is WCAG 1.4.11 and a different population: borders, icons,
# state indicators, focus rings, chart strokes. `probeContrast()` walks text
# nodes only, so a 1.4.11 figure is legitimately absent from its records.
NONTEXT_CONTEXT = re.compile(
    r"(1\.4\.11|non-?text|hairline|border|outline|icon|stroke|chart|divider|rule|"
    r"focus ring|state indicator|graphical object)", re.I)



def cmd_claims(args) -> int:
    workdir = Path(args.workdir).resolve()
    report = Path(args.report).resolve()
    if not report.exists():
        sys.exit(f"No report at {report}")
    probes = load_probes(workdir)

    # A review often captures extra widths into a sibling workdir — `wd-320`
    # beside `wd` — and those captures are on record even though they are not in
    # this manifest. Reading one manifest made the gate report an observation at
    # 320px as unsupported while the 320px screenshot sat on disk. A gate that
    # fires on correct work gets switched off.
    manifests = []
    for mf in sorted(set(list(workdir.parent.glob("*/manifest.json")) +
                         list(workdir.glob("manifest.json")))):
        try:
            manifests.append(json.loads(mf.read_text()))
        except json.JSONDecodeError:
            print(f"! {mf} is not valid JSON — its captures cannot support any claim",
                  file=sys.stderr)
    sibling_probes = {}
    for pf in sorted(workdir.parent.glob("*/probes/*.json")):
        try:
            sibling_probes[str(pf)] = json.loads(pf.read_text())
        except json.JSONDecodeError:
            pass
    all_probes = {**sibling_probes, **probes}
    text = report.read_text()

    # What the run can actually support.
    def maxof(fn):
        vals = [fn(p) for p in all_probes.values()]
        vals = [v for v in vals if isinstance(v, (int, float))]
        return max(vals) if vals else 0

    supported = {
        "component_types": maxof(
            lambda p: ((p.get("layout") or {}).get("inventory") or {}).get("distinctTypes")),
        "contrast_failures": maxof(
            lambda p: (p.get("contrast") or {}).get("failureCount")
            if isinstance(p.get("contrast"), dict) else None),
        "examined": maxof(
            lambda p: (p.get("contrast") or {}).get("examined")
            if isinstance(p.get("contrast"), dict) else None),
    }

    # Every ratio the run recorded — for passing elements as well as failing
    # ones, and every stop of a gradient rather than only the worst. A review
    # legitimately quotes "the body text is fine at 8.3:1" and legitimately
    # quotes the stops it scored across; both were being called fabrications
    # because the probe only wrote down its failures.
    ratios = set()
    for p in all_probes.values():
        c = p.get("contrast")
        if not isinstance(c, dict):
            continue
        for rec in (c.get("ratios") or []) + (c.get("failures") or []):
            if not isinstance(rec, dict):
                continue
            if rec.get("ratio") is not None:
                ratios.add(round(float(rec["ratio"]), 2))
            for s in rec.get("stops") or []:
                ratios.add(round(float(s), 2))

    print(f"Claims audit — {report.name} against {workdir}\n")
    problems: list[str] = []
    skipped_fix = 0
    skipped_nontext = 0

    for kind, rx in CLAIM_PATTERNS:
        for m in rx.finditer(text):
            if kind == "contrast_ratio":
                v = round(float(m.group(1)), 2)
                # The formula's own bounds, and the WCAG floors. A report that
                # writes "needs 4.5:1" is quoting a threshold, not claiming a
                # measurement, and treating those as claims made the gate fire on
                # every correctly-cited requirement in the document.
                if v in (1.0, 21.0) or v in WCAG_THRESHOLDS:
                    continue
                # The sentence around it decides whether it is a claim at all.
                window = text[max(0, m.start() - 140):m.end() + 60]
                if FIX_CONTEXT.search(window):
                    skipped_fix += 1
                    continue
                if NONTEXT_CONTEXT.search(window):
                    skipped_nontext += 1
                    continue
                if not any(abs(v - r) <= 0.05 for r in ratios):
                    problems.append(
                        f"report quotes {v}:1, which no probe record within 0.05 supports "
                        f"(recorded: {sorted(ratios) or 'none'})")
            elif kind == "component_types":
                opened, total = int(m.group(1)), int(m.group(2))
                if total != supported["component_types"]:
                    problems.append(
                        f"report claims a component denominator of {total}; the inventory "
                        f"found {supported['component_types']}")
                if opened > total:
                    problems.append(f"report claims {opened} of {total} component types "
                                    f"opened — a numerator above its denominator")
            elif kind == "surfaces":
                done, total = int(m.group(1)), int(m.group(2))
                # The ledger may sit in the workdir or beside it, depending on
                # where `worklist.py init` was pointed.
                ledger = next((p for p in (workdir / "worklist.md",
                                           workdir.parent / "worklist.md") if p.exists()), None)
                if ledger:
                    rows = [l for l in ledger.read_text().splitlines()
                            if l.strip().startswith("|") and re.match(r"\|\s*\d+\s*\|", l)]
                    if rows and total != len(rows):
                        problems.append(
                            f"report claims {total} surfaces; the stage-0 ledger at {ledger} "
                            f"fixed {len(rows)}. A denominator set after the fact always "
                            f"equals its numerator.")
                elif total > 1:
                    problems.append(f"report claims {done} of {total} surfaces but there is "
                                    f"no worklist.md in {workdir} or its parent to fix that "
                                    f"denominator")
            elif kind in ("contrast_failures", "examined"):
                v = int(m.group(1))
                if v > supported[kind]:
                    problems.append(f"report claims {v} for {kind}; the run recorded at most "
                                    f"{supported[kind]}")

    # A rendered observation over captures that were never taken.
    shots = {s for man in manifests for v in man.get("viewports", [])
             for s in (v.get("shots") or {}).values()}
    tiles = sum(len(v.get("tiles") or []) for man in manifests
                for v in man.get("viewports", []))

    # The "47 buttons" check. Every element population the run counted, from the
    # component inventory, so a claimed count can be tested against a measured
    # one. The inventory is the deterministic collector the research recommends:
    # a count generated by code, never by prose.
    inventory_pop: dict[str, int] = {}
    total_instances = 0
    for p in all_probes.values():
        inv = ((p.get("layout") or {}).get("inventory") or {})
        for t in inv.get("types") or []:
            if not isinstance(t, dict):
                continue
            name = str(t.get("type") or t.get("name") or "").lower()
            n = t.get("count") or t.get("instances") or 0
            if name:
                inventory_pop[name] = max(inventory_pop.get(name, 0), int(n))
                total_instances = max(total_instances, sum(inventory_pop.values()))
    dom_total = max([((p.get("layout") or {}).get("inventory") or {}).get("totalInstances") or 0
                     for p in all_probes.values()] or [0])
    # Every population this run counted, not just the inventory. A review
    # legitimately writes "18 elements pass" straight off `contrast.passCount`,
    # and comparing that against the inventory's instance total rejected the
    # gate's own footer figure.
    other_counts = [0]
    for p in all_probes.values():
        c = p.get("contrast")
        if isinstance(c, dict):
            other_counts += [c.get("examined") or 0, c.get("passCount") or 0,
                             c.get("failureCount") or 0]
        for seq in (p.get("targets"), p.get("images"), p.get("styles")):
            if isinstance(seq, list):
                other_counts.append(len(seq))
    ceiling = max(total_instances, dom_total, len(shots), max(other_counts))

    for m in ELEMENT_CLAIM.finditer(text):
        claimed = int(m.group(1))
        noun = re.sub(r"\s+", " ", m.group(2).lower()).rstrip("s")
        measured = next((v for k, v in inventory_pop.items() if noun in k), None)
        if measured is not None and claimed > measured:
            problems.append(f"report claims {claimed} {m.group(2)}; the inventory counted "
                            f"{measured}")
        elif measured is None and ceiling and claimed > ceiling:
            problems.append(f"report claims {claimed} {m.group(2)}, which exceeds every "
                            f"population this run measured (largest: {ceiling}). Nothing in "
                            f"the run produced that number.")
        elif measured is None and not ceiling:
            problems.append(f"report claims {claimed} {m.group(2)} but the run recorded no "
                            f"inventory to support any element count")

    for m in re.finditer(r"\b(\d+)\s+(?:crops?|captures?|screenshots?)\b", text, re.I):
        claimed = int(m.group(1))
        available = len(shots) + tiles
        if claimed > available:
            problems.append(f"report claims {claimed} captures opened; the manifest records "
                            f"{available}")

    # Viewport widths asserted but never captured.
    captured_widths = {str(v.get("viewport", "")).split("x")[0]
                       for man in manifests for v in man.get("viewports", [])}
    for m in re.finditer(r"\bat\s+(\d{3,4})\s*px\b", text, re.I):
        w = m.group(1)
        if captured_widths and w not in captured_widths:
            problems.append(f"report asserts an observation at {w}px; captured widths are "
                            f"{sorted(captured_widths)}")

    if skipped_fix or skipped_nontext:
        print(f"  ratios not treated as claims: {skipped_fix} attached to a proposed fix, "
              f"{skipped_nontext} non-text (1.4.11)")
        print("  (excluded deliberately — a replacement colour is not on the page yet, and "
              "non-text\n   contrast is a population probeContrast does not walk)")
    print(f"  inventory denominator: {supported['component_types']}")
    print(f"  contrast: {supported['contrast_failures']} failures of "
          f"{supported['examined']} examined")
    print(f"  distinct recorded ratios: {len(ratios)}")
    print(f"  captures on record: {len(shots)}")
    print()

    # One entry per DISTINCT problem, with its occurrence count beside it.
    # Measured 18 Aug 2026: counting occurrences meant adding one provenance
    # bullet took a report from 20 flags to 27 — the gate scored a reviewer worse
    # for saying where a number came from. Deduplicating is not cosmetic; it is
    # what stops the gate arguing against its own purpose.
    from collections import Counter
    tally = Counter(problems)
    if problems:
        print(f"FAIL — {len(tally)} distinct claim(s) the run does not support "
              f"({len(problems)} mention(s)):", file=sys.stderr)
        for msg, n in tally.most_common():
            suffix = f"  [x{n}]" if n > 1 else ""
            print(f"  · {msg}{suffix}", file=sys.stderr)
        print("\nA number in a review is a measurement or it is nothing. Fix the claim or "
              "take\nthe measurement — do not soften the wording.", file=sys.stderr)
        return 1
    print("PASS — every quantified claim traces to the run.")
    print("\nThis checks arithmetic against the manifest, not whether a finding is right.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Audit a review run: which zeros are real, and which claims are earned.")
    sub = ap.add_subparsers(dest="mode", required=True)

    c = sub.add_parser("capability", help="Split every headline metric into measured / "
                                          "declared / unmeasurable. Exits 1 on an "
                                          "unmeasurable metric a report would quote.")
    c.add_argument("workdir")
    c.set_defaults(fn=cmd_capability)

    k = sub.add_parser("claims", help="Check the written report's numbers against the run. "
                                      "Exits 1 on a claim the manifest cannot support.")
    k.add_argument("workdir")
    k.add_argument("--report", required=True, help="The written report to audit.")
    k.set_defaults(fn=cmd_claims)

    args = ap.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
